# Generated by Django 5.1 on 2024-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
