# Generated by Django 5.1 on 2024-08-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_wishlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
