# Generated by Django 5.1 on 2024-08-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
