# Generated by Django 5.1 on 2024-08-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
