# Generated by Django 5.0.8 on 2024-08-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_profile_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
